### ISSUE TITLE
Misprints & Omissions

### ISSUE THREAD

**Issue by JohnP2137** [TDStrasser/KookaBlockly-Reference#5]
1. Important Note in Neopixel description: missing "to" in 1st sentience
2. RGB Values missing "e" in range
3. Note in Pins palette" missing "of' in 1st sentence
4. Get compass: Formatting.....
5. Get soil moisture: 3rd para "soil's". Also, last but one sentence "values" plural
6. Set servo to angle taking seconds: Item 1> "select" not "selected". Same typo in next two blocks
7. Log to file: Third para. > "by default". Fourth para> "are also" rather than "also are"? **ALSO** you have only two of the three blocks pictured. The first one is repeated.
8. Format as an integer: Second dot point suffers by the example wrapping into the next line
9. Length of List: Very small issue but display print block is not as shown in Display palette..... Same in following examples
10. List Blocks General: Are the pics of blocks getting bigger? Also pics are becoming distorted.
11. Make List/Text with Delimiter: Item 2 concatenate singular
12. Scale Function: Second para "freezing point"
13. Variables: 3rd para "for" not "fro". 
14. Variable Value: The example is described as sampling every 5 secs but the graphic shows every 1 sec

**Comment by TDStrasser** [comment]
Thanks John.
If you can, please keep to one blocks category per post.  It's difficult to handle so many things and keep track.
All the issues listed have been remedied.
1. fixed
2. fixed
3. fixed
4. fixed
5. fixed
6. fixed
7. both issues fixed
8. fixed (errant space)
9. The issue is with the Display palette - updated to latest version of KookaBlockly (but not yet released via GitHub)
10. Yes they were - have tried to address.
11. fixed
12. fixed
13. fixed
14. fixed - changed the graphic

I'll do an update of Read the Docs later today
